### ISSUE TITLE
comformity with etcdctl

### ISSUE THREAD

**Issue by akd31** [soyking/e3w#3]
When I put key value with etcdctl I couldn't see them on this web ui. Likewise, I couldn't get with etcdctl kvs which I put via this web ui.

**Comment by soyking** [comment]
In order to mange keys like folders, every key you set on the website will be added the prefix of `root_key`, which is set on `conf/config.ini`.

So if:

- you want to see the key you set by etcdctl, you should make the key like `e3w_test/abc/def`

- you want to get the key you set on website by etcdctl, you should try something like `ETCDCTL_API=3 etcdctl get --prefix e3w_test`

**Comment by akd31** [comment]
Thanks
